
  # 各省份新闻政策 新闻-发展和改革委员会-福建
  spider_province_policy_news_news_fgw_fujian:
    <<: *common_spider_config
    container_name: spider_province_policy_news_news_fgw_fujian
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n news_fgw_fujian

  # 各省份新闻政策 新闻-发展和改革委员会-甘肃
  spider_province_policy_news_news_fgw_gansu:
    <<: *common_spider_config
    container_name: spider_province_policy_news_news_fgw_gansu
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n news_fgw_gansu

  # 各省份新闻政策 新闻-发展和改革委员会-河南
  spider_province_policy_news_news_fgw_henan:
    <<: *common_spider_config
    container_name: spider_province_policy_news_news_fgw_henan
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n news_fgw_henan

  # 各省份新闻政策 新闻-发展和改革委员会-江苏
  spider_province_policy_news_news_fgw_jiangsu:
    <<: *common_spider_config
    container_name: spider_province_policy_news_news_fgw_jiangsu
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n news_fgw_jiangsu

  # 各省份新闻政策 新闻-发展和改革委员会-浙江
  spider_province_policy_news_news_fgw_zhejiang:
    <<: *common_spider_config
    container_name: spider_province_policy_news_news_fgw_zhejiang
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n news_fgw_zhejiang

  # 各省份新闻政策 新闻-国家能源局-甘肃
  spider_province_policy_news_news_gsbnea:
    <<: *common_spider_config
    container_name: spider_province_policy_news_news_gsbnea
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n news_gsbnea

  # 各省份新闻政策 新闻-工业和信息化厅-江西
  spider_province_policy_news_news_gxt_jiangxi:
    <<: *common_spider_config
    container_name: spider_province_policy_news_news_gxt_jiangxi
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n news_gxt_jiangxi

  # 各省份新闻政策 新闻-国家能源局-福建
  spider_province_policy_news_news_nea_fujian:
    <<: *common_spider_config
    container_name: spider_province_policy_news_news_nea_fujian
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n news_nea_fujian

  # 各省份新闻政策 新闻-国家能源局-江苏
  spider_province_policy_news_news_nea_jiangsu:
    <<: *common_spider_config
    container_name: spider_province_policy_news_news_nea_jiangsu
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n news_nea_jiangsu

  # 各省份新闻政策 新闻-国家能源局-四川
  spider_province_policy_news_news_scbnea:
    <<: *common_spider_config
    container_name: spider_province_policy_news_news_scbnea
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n news_scbnea

  # 各省份新闻政策 新闻-生态环境厅-福建
  spider_province_policy_news_news_sthjt_fujian:
    <<: *common_spider_config
    container_name: spider_province_policy_news_news_sthjt_fujian
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n news_sthjt_fujian

  # 各省份新闻政策 新闻-生态环境厅-陕西
  spider_province_policy_news_news_sthjt_shaanxi:
    <<: *common_spider_config
    container_name: spider_province_policy_news_news_sthjt_shaanxi
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n news_sthjt_shaanxi

  # 各省份新闻政策 新闻-生态环境厅-四川
  spider_province_policy_news_news_sthjt_sichuan:
    <<: *common_spider_config
    container_name: spider_province_policy_news_news_sthjt_sichuan
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n news_sthjt_sichuan

  # 各省份新闻政策 新闻-发展和改革委员会-四川
  spider_province_policy_news_new_fgw_sichuan:
    <<: *common_spider_config
    container_name: spider_province_policy_news_new_fgw_sichuan
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n new_fgw_sichuan

  # 各省份新闻政策 政策-发展和改革委员会-重庆
  spider_province_policy_news_policy_fgw_chongqing:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_fgw_chongqing
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_fgw_chongqing

  # 各省份新闻政策 政策-发展和改革委员会-河南
  spider_province_policy_news_policy_fgw_henan:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_fgw_henan
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_fgw_henan

  # 各省份新闻政策 政策-发展和改革委员会-江苏
  spider_province_policy_news_policy_fgw_jiangsu:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_fgw_jiangsu
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_fgw_jiangsu

  # 各省份新闻政策 政策-发展和改革委员会-陕西
  spider_province_policy_news_policy_fgw_shaanxi:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_fgw_shaanxi
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_fgw_shaanxi

  # 各省份新闻政策 政策-发展和改革委员会-浙江
  spider_province_policy_news_policy_fgw_zhejiang:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_fgw_zhejiang
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_fgw_zhejiang

  # 各省份新闻政策 政策-发展和改革委员会-湖南
  spider_province_policy_news_policy_fgw_hunan:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_fgw_hunan
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_fgw_hunan

  # 各省份新闻政策 政策-发展和改革委员会-四川
  spider_province_policy_news_policy_fgw_sichuan:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_fgw_sichuan
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_fgw_sichuan

  # 各省份新闻政策 政策-国家能源局-甘肃
  spider_province_policy_news_policy_gsbnea:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_gsbnea
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_gsbnea

  # 各省份新闻政策 政策-工业和信息化厅-福建
  spider_province_policy_news_policy_gxt_fujian:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_gxt_fujian
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_gxt_fujian

  # 各省份新闻政策 政策-工业和信息化厅-湖南
  spider_province_policy_news_policy_gxt_hunan:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_gxt_hunan
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_gxt_hunan

  # 各省份新闻政策 政策-工业和信息化厅-河南
  spider_province_policy_news_policy_gxt_henan:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_gxt_henan
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_gxt_henan

  # 各省份新闻政策 政策-工业和信息化厅-江苏
  spider_province_policy_news_policy_gxt_jiangsu:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_gxt_jiangsu
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_gxt_jiangsu

  # 各省份新闻政策 政策-工业和信息化厅-江西
  spider_province_policy_news_policy_gxt_jiangxi:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_gxt_jiangxi
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_gxt_jiangxi

  # 各省份新闻政策 政策-工业和信息化厅-陕西
  spider_province_policy_news_policy_gxt_shaanxi:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_gxt_shaanxi
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_gxt_shaanxi

  # 各省份新闻政策 政策-能源发展厅-河南
  spider_province_policy_news_policy_hnnyfz:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_hnnyfz
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_hnnyfz

  # 各省份新闻政策 政策-国家能源局-湖北
  spider_province_policy_news_policy_hunb_nea:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_hunb_nea
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_hunb_nea

  # 各省份新闻政策 政策-国家能源局-福建
  spider_province_policy_news_policy_nea_fujian:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_nea_fujian
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_nea_fujian

  # 各省份新闻政策 政策-国家能源局-陕西
  spider_province_policy_news_policy_nea_shaanxi:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_nea_shaanxi
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_nea_shaanxi

  # 各省份新闻政策 政策-国家能源局-江苏
  spider_province_policy_news_policy_nea_jiangsu:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_nea_jiangsu
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_nea_jiangsu

  # 各省份新闻政策 政策-国家能源局-浙江
  spider_province_policy_news_policy_nea_zhejiang:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_nea_zhejiang
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_nea_zhejiang

  # 各省份新闻政策 政策-国家能源局-四川
  spider_province_policy_news_policy_scbnea:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_scbnea
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_scbnea

  # 各省份新闻政策 政策-经济和信息化委员会-重庆
  spider_province_policy_news_policy_jjxxw_chongqing:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_jjxxw_chongqing
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_jjxxw_chongqing

  # 各省份新闻政策 政策-交通运输厅-四川
  spider_province_policy_news_policy_jxt_sichuan:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_jxt_sichuan
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_jxt_sichuan

  # 各省份新闻政策 政策-发展和改革委员会-陕西（能源处）
  spider_province_policy_news_policy_sndrc_shaanxi:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_sndrc_shaanxi
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_sndrc_shaanxi

  # 各省份新闻政策 政策-生态环境厅-重庆
  spider_province_policy_news_policy_sthjt_chongqing:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_sthjt_chongqing
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_sthjt_chongqing

  # 各省份新闻政策 政策-生态环境厅-福建
  spider_province_policy_news_policy_sthjt_fujian:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_sthjt_fujian
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_sthjt_fujian

  # 各省份新闻政策 政策-生态环境厅-湖南
  spider_province_policy_news_policy_sthjt_hunan:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_sthjt_hunan
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_sthjt_hunan

  # 各省份新闻政策 政策-生态环境厅-陕西
  spider_province_policy_news_policy_sthjt_shaanxi:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_sthjt_shaanxi
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_sthjt_shaanxi

  # 各省份新闻政策 政策-生态环境厅-四川
  spider_province_policy_news_policy_sthjt_sichuan:
    <<: *common_spider_config
    container_name: spider_province_policy_news_policy_sthjt_sichuan
    volumes:
      - ./province_policy_news:/app
    command: python start.py -n policy_sthjt_sichuan
